version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    restart: unless-stopped
    mem_limit: 300m
    memswap_limit: 500m
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge 
